version: '3'
services:
  delegation-service:
    image: delegation-service:latest
    build: .
    ports:
      - '8080:8080'
    env_file:
      - ../kdrive.env

  terminal-mock-api:
    image: registry.gitlab.com/yesodot/shared-projects/dropbox/terminal-mock-api
    environment:
      NODE_ENV: production
      PORT: 8080
    ports:
      - '8082:8080'

  mongo:
    image: mongo:4.0.9
    ports:
      - "27017:27017"
    volumes:
      - ../data/db:/data/db
